{% set name = "openTSNE" %}
{% set version = "0.4.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 66128744219e5ef6c6b4c9309285158a63ef88e4f57b023427a8d7181e79df50

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  skip: True  # [py<35]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - numpy ==1.14.6
    - pip
    - python
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - scikit-learn >=0.20
    - scipy

test:
  imports:
    - openTSNE

about:
  home: https://github.com/pavlin-policar/openTSNE
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Extensible, parallel implementations of t-SNE
  doc_url: https://opentsne.readthedocs.io
  dev_url: https://github.com/pavlin-policar/openTSNE

extra:
  recipe-maintainers:
    - pavlin-policar
