{% set name = "openTSNE" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 253698f39242af883cc79f6e6764f311c4e988a0f3c5e4c7a49e9ce0851d2694

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  skip: true  # [py<35]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy ==1.14.6
    - pip
    - python
  run:
    - {{ pin_compatible('numpy') }}
    - numba >=0.38.1
    - python
    - scikit-learn >=0.20
    - scipy
    - pynndescent >=0.3

test:
  imports:
    - openTSNE

about:
  home: https://github.com/pavlin-policar/openTSNE
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Extensible, parallel implementations of t-SNE
  doc_url: https://opentsne.readthedocs.io
  dev_url: https://github.com/pavlin-policar/openTSNE

extra:
  recipe-maintainers:
    - pavlin-policar
