{% set name = "openTSNE" %}
{% set version = "0.3.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a6ad8104997697cdbe5c413ce0c3e3b0d1970c696fc01ebe468e1dd468c2185f

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  skip: True  # [py<35]

requirements:
  build:
    - {{ compiler('c') }}
    - fftw
    - openmp
  host:
    - numpy
    - pip
    - python
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - scikit-learn >=0.20
    - scipy
    - pynndescent >=0.3

test:
  imports:
    - openTSNE

about:
  home: https://github.com/pavlin-policar/openTSNE
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Extensible, parallel implementations of t-SNE
  doc_url: https://opentsne.readthedocs.io
  dev_url: https://github.com/pavlin-policar/openTSNE

extra:
  recipe-maintainers:
    - pavlin-policar
