{% set name = "openTSNE" %}
{% set version = "0.3.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7707411578babc9619ba2d50b16386c48e2081a0d666d6a1611fa1e2fd208304

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  skip: True  # [py<35]

requirements:
  build:
    - {{ compiler('c') }}
    - fftw
    - openmp
  host:
    - numpy
    - pip
    - python
  run:
    - {{ pin_compatible('numpy') }}
    - numba >=0.38.1
    - python
    - scikit-learn >=0.20
    - scipy

test:
  imports:
    - openTSNE

about:
  home: https://github.com/pavlin-policar/openTSNE
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Extensible, parallel implementations of t-SNE
  doc_url: https://opentsne.readthedocs.io
  dev_url: https://github.com/pavlin-policar/openTSNE

extra:
  recipe-maintainers:
    - pavlin-policar
