appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: vvqBdqitIjDh9/AoVTJBeKiRgQcUaHLLt6LxUE32mwMkC3Kee0OOsq8Wz5y1NrWxJbS/XflT+4fKD68gbp+WLTBg8+nCNXGtXBPmrgKEXm/fl3mkMO22WfOQ9NG/aCvstaHLdbDKdEIf37Lw+e8OWow1XSuKkYqaWJQ+Ev7jtdU3545dPbKsdQPOt+ScHLHg3w2gkabXV4aZNH8avgHRiaQakCQ3ep5qgtIYMT+kIJeVf0Dh/Cq/VFfyPuJGQBJ2qJ5rvjdcSTKAdUYhj+nfLOFS8DswWyLMoPiK8e9PrNYfTjMR7rZBi4ZlvARFlRrQMWVolyXaYNdVoWNWkylVs0j8hX+S+UIb40JdLD8ZspxiFLKPcmg4omFOYSjVYXsNg+MaNBIXTF0o2qbTJfomVeFMtXCQXDQ41kO3S59RD25WLaNucNuaMHTiwv2JXoCRvM/IYOTzQwGaiG/a7ABtQUH0iqUGPPJeetlVBwSqSiEsW6kCE7Z1Ui+MHFEH/sBRbEy1K27z30nTQdM2boEJ+/jm7BkuM1Q+VPi9heJFH+OHQ3bBdcWipvknLN93PC0OdKS3qwuOl7++TnERci3sp5Miw2K5fV01zyypo1BZC4dxnYL6kBIuMU55322XCvWVgwUqctEdVMP7MZc3Q/rQjyVoWZDvZRTcpbshuGNaK/k=}
